### ISSUE TITLE
please

### ISSUE THREAD

**Issue by SAV-404** [MineMooreALT/MineMooreALT.github.io#2]
is this client free to use??
i wanna use it on my extention and change some stufs

**Comment by MineMooreALT** [comment]
As long as you credit yes if you don't credit you will be taken down

**Comment by SAVAGE2001** [comment]
you mean i have to show who made it??..........it's ok @MineMooreALT  ...by the way i'm your fan 😘😘

**Comment by MineMooreALT** [comment]
Yes, :d

**Comment by SAV-404** [comment]
![capture](https://cloud.githubusercontent.com/assets/26459304/25701500/9d82cb7c-30c4-11e7-8252-c9655fe6088e.PNG)

this is what should i do?? i mean i don't have to delet it
just tell me please what do i have to do to credit

**Comment by MineMooreALT** [comment]
Keep everything and credit me tho if you make it a vid or something

**Comment by SAV-404** [comment]
understood😉
